repos:
  - repo: local
    hooks:
      - id: pytests-local
        name: Run unit tests
        entry: bash -c "pytest || [ $? -eq 5 ]"
        language: system
        pass_filenames: false
        always_run: true
  
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black